#!/bin/sh -ex

DB_NAME=wetkit
DB_USER=wetkit
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=WetKit@2013

SRC=/usr/local/src
WEBROOT=/var/www/wetkit

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli memory limit (for drush)
sed -i "s|^memory_limit.*|memory_limit = 128M|" /etc/php5/cli/php.ini

# increase php memory limit (for drupal)
sed -i "s|^memory_limit.*|memory_limit = 256M|" /etc/php5/apache2/php.ini

# install drush and configure
pear channel-discover pear.drush.org
pear install drush/drush

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

# download latest wetkit release
wget -O /tmp/wetkit.tar.gz http://ftp.drupal.org/files/projects/wetkit-7.x-1.2-core.tar.gz

# untar and move to web root
tar -zxvf /tmp/wetkit.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/wetkit-7.x-1.2 $WEBROOT

# create default settings file
SETTINGS=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $SETTINGS
chown www-data:www-data $SETTINGS

/etc/init.d/mysql start

# install wetkit drupal
drush si wetkit wetkit_theme_selection_form.theme=wetkit_omega install_configure_form.demo_content=TRUE \
	--sites-subdir=default \
	--db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME \
	--account-name=$ADMIN_NAME \
	--account-pass=$ADMIN_PASS \
	--site-mail=admin@example.com \
	--site-name='Web Experience Toolkit' \
	--yes

chown root:www-data $SETTINGS
chmod 640 $SETTINGS
chown -R www-data:www-data $WEBROOT/sites/default/files

chown -R root:root $WEBROOT/sites/all

# disable poor mans cron and setup drush cron
cat >>$WEBROOT/sites/default/settings.php<< EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 7 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 * by setting the cron_safe_threshold to 0.
 *
 * To re-enable Poor Man's Cron:
 *    Comment out (add a leading hash sign) the line below,
 *    and the system cron in /etc/cron.d/drupal7.
 */
\$conf['cron_safe_threshold'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/wetkit
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron
# Alternatively Drupal's poor mans cron: sites/default/settings.php

[ -x /usr/bin/drush ] || exit 0

su www-data -c "/usr/bin/drush --quiet cron"
EOF
chmod +x $CRON_DRUPAL

/etc/init.d/mysql stop

# configure apache
a2dissite default
a2ensite wetkit
a2enmod rewrite

# unset proxy settings
unset HTTP_PROXY
