#!/bin/bash -e
# regenerate drupal7 hash_salt and mysql password

. /etc/default/inithooks

CONF=/var/www/wetkit/sites/default/settings.php

SALT=$(mcookie)
sed -i "s|^\$drupal_hash_salt = \(.*\)|\$drupal_hash_salt = '$SALT';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|^      'password'\(.*\)|      'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=wetkit --pass="$PASSWORD"

